driver: com.mysql.cj.jdbc.Driver
url: jdbc:mysql://snowman-mysql.mysql.database.azure.com:3306/snowman?nullNamePatternMatchesAll=true&useSSL=true
username: snowmanadmin
password: Snowman#2026Db
verbose: true
dropFirst: false
changeLogFile: /src/main/resources/db/liquibase-changelog-schema.xml
